package docsgen

import (
	"bytes"
	"context"
	"crypto/sha256"
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/joshyorko/camp/internal/cli"
	"github.com/joshyorko/camp/internal/doctor"
	"github.com/spf13/cobra"
)

// Generate renders repository documentation artifacts directly from the
// production Cobra tree. Paths are repository-relative and stable.
func Generate(root *cobra.Command) (map[string][]byte, error) {
	files := make(map[string][]byte)
	commands, err := commandReference(root)
	if err != nil {
		return nil, err
	}
	files["docs/generated/commands.md"] = commands
	transcripts, err := transcriptReference()
	if err != nil {
		return nil, err
	}
	files["docs/generated/transcripts.md"] = transcripts
	presentation, err := presentationReference()
	if err != nil {
		return nil, err
	}
	files["docs/generated/presentation.md"] = presentation
	for _, shell := range []cli.Shell{cli.ShellBash, cli.ShellZsh, cli.ShellFish} {
		var output bytes.Buffer
		if err := cli.GenerateCompletion(root, shell, &output); err != nil {
			return nil, fmt.Errorf("generate %s completion: %w", shell, err)
		}
		files[fmt.Sprintf("docs/generated/completions/camp.%s", shell)] = output.Bytes()
	}
	return files, nil
}

func presentationReference() ([]byte, error) {
	report := doctor.NewReport([]doctor.Result{{
		Capability: "pasta", Status: doctor.StatusBlocked, Code: "pasta_missing",
		Summary: "pasta is unavailable", Remediation: "install passt outside Camp, then rerun camp doctor",
	}})
	var human, json bytes.Buffer
	if err := doctor.RenderHuman(&human, report); err != nil {
		return nil, err
	}
	if err := doctor.RenderJSON(&json, report); err != nil {
		return nil, err
	}
	var output bytes.Buffer
	output.WriteString("<!-- Code generated by go run ./cmd/camp-docs; DO NOT EDIT. -->\n\n")
	output.WriteString("# Versioned presentation examples\n\n")
	output.WriteString("Both examples render the same deterministic doctor model. They demonstrate the presentation contract, not the current host's health.\n\n## Human\n\n```text\n")
	output.Write(human.Bytes())
	output.WriteString("```\n\n## JSON\n\n```json\n")
	output.Write(json.Bytes())
	output.WriteString("```\n")
	return output.Bytes(), nil
}

type Invocation struct {
	CommandPath string
	Args        []string
}

// DocumentedInvocations is the deterministic, effect-free equivalent used to
// prove every public command can be parsed and dispatched.
func DocumentedInvocations() []Invocation {
	return []Invocation{
		{CommandPath: "camp", Args: []string{"--help"}},
		{CommandPath: "camp attach", Args: []string{"attach", "memoryd"}},
		{CommandPath: "camp close", Args: []string{"close"}},
		{CommandPath: "camp completion", Args: []string{"completion", "bash"}},
		{CommandPath: "camp doctor", Args: []string{"doctor"}},
		{CommandPath: "camp init", Args: []string{"init", "/tmp/camp-docs-capsule", "--name", "docs-capsule"}},
		{CommandPath: "camp list", Args: []string{"list"}},
		{CommandPath: "camp open", Args: []string{"open", "memoryd"}},
		{CommandPath: "camp recover", Args: []string{"recover", "memoryd"}},
		{CommandPath: "camp reopen", Args: []string{"reopen", "memoryd"}},
		{CommandPath: "camp setup", Args: []string{"setup"}},
		{CommandPath: "camp status", Args: []string{"status", "--camp", "memoryd"}},
		{CommandPath: "camp strike", Args: []string{"strike"}},
		{CommandPath: "camp sync", Args: []string{"sync"}},
	}
}

func transcriptReference() ([]byte, error) {
	var output bytes.Buffer
	output.WriteString("<!-- Code generated by go run ./cmd/camp-docs; DO NOT EDIT. -->\n\n")
	output.WriteString("# Deterministic command transcripts\n\n")
	output.WriteString("These transcripts execute the real Cobra parsing and dispatch tree against an effect-free documentation lifecycle. `docsgen` output proves syntax and wiring only; it is not DevPod, backend, checkpoint, or release evidence.\n\n")
	for _, invocation := range DocumentedInvocations() {
		var stdout, stderr bytes.Buffer
		code := cli.Execute(context.Background(), transcriptRoot(), invocation.Args, cli.Streams{Out: &stdout, ErrOut: &stderr})
		if code != 0 {
			return nil, fmt.Errorf("execute %s: exit %d: %s", invocation.CommandPath, code, stderr.String())
		}
		output.WriteString("## `" + strings.Join(append([]string{"camp"}, invocation.Args...), " ") + "`\n\n```console\n$ camp " + strings.Join(invocation.Args, " ") + "\n")
		if invocation.CommandPath == "camp completion" {
			fmt.Fprintf(&output, "generated bash completion: %d bytes, sha256 %x\n", stdout.Len(), sha256.Sum256(stdout.Bytes()))
		} else {
			output.Write(stdout.Bytes())
		}
		output.Write(stderr.Bytes())
		output.WriteString("```\n\n")
	}
	return bytes.TrimSuffix(output.Bytes(), []byte("\n")), nil
}

type transcriptLifecycle struct{}

func fixtureDispatch(output io.Writer, command string) error {
	_, err := fmt.Fprintf(output, "effect-free docs fixture: %s dispatched; external effects disabled\n", command)
	return err
}
func (transcriptLifecycle) Init(_ context.Context, _ cli.InitRequest, _ cli.OutputMode, output io.Writer) error {
	return fixtureDispatch(output, "init")
}
func (transcriptLifecycle) Open(_ context.Context, _ string, _ cli.OutputMode, output io.Writer) error {
	return fixtureDispatch(output, "open")
}
func (transcriptLifecycle) Attach(_ context.Context, _ cli.AttachRequest, _ cli.OutputMode, output io.Writer) error {
	return fixtureDispatch(output, "attach")
}
func (transcriptLifecycle) Sync(_ context.Context, _ cli.OutputMode, output io.Writer) error {
	return fixtureDispatch(output, "sync")
}
func (transcriptLifecycle) Close(_ context.Context, _ cli.CloseRequest, _ cli.OutputMode, output io.Writer) error {
	return fixtureDispatch(output, "close")
}
func (transcriptLifecycle) Reopen(_ context.Context, _ string, _ cli.OutputMode, output io.Writer) error {
	return fixtureDispatch(output, "reopen")
}
func (transcriptLifecycle) Recover(_ context.Context, _ string, _ cli.OutputMode, output io.Writer) error {
	return fixtureDispatch(output, "recover")
}
func (transcriptLifecycle) Setup(_ context.Context, _ cli.OutputMode, _ io.Reader, output io.Writer) error {
	return fixtureDispatch(output, "setup")
}
func (transcriptLifecycle) Supervise(_ context.Context, _ string, _ cli.OutputMode, output io.Writer) error {
	return fixtureDispatch(output, "supervise")
}
func (transcriptLifecycle) Doctor(_ context.Context, _ cli.OutputMode, output io.Writer) error {
	return fixtureDispatch(output, "doctor")
}
func (transcriptLifecycle) List(_ context.Context, _ cli.OutputMode, output io.Writer) error {
	return fixtureDispatch(output, "list")
}
func (transcriptLifecycle) Status(_ context.Context, _ cli.OutputMode, output io.Writer) error {
	return fixtureDispatch(output, "status")
}
func (transcriptLifecycle) Strike(_ context.Context, _ cli.StrikeRequest, _ cli.OutputMode, output io.Writer) error {
	return fixtureDispatch(output, "strike")
}

func transcriptRoot() *cobra.Command { return cli.NewRootWithLifecycle(transcriptLifecycle{}) }

func commandReference(root *cobra.Command) ([]byte, error) {
	var output bytes.Buffer
	output.WriteString("<!-- Code generated by go run ./cmd/camp-docs; DO NOT EDIT. -->\n\n")
	output.WriteString("# Camp command reference\n\n")
	output.WriteString("This reference is generated from the production Cobra tree. A listed command is wired, but its presence is not evidence that external tools or a complete lifecycle succeeded.\n\n")
	commands := visibleCommands(root)
	for _, command := range commands {
		output.WriteString("## `" + command.CommandPath() + "`\n\n")
		output.WriteString(command.Short + "\n\n")
		output.WriteString("```text\nUsage:\n  " + command.UseLine() + "\n")
		command.InitDefaultHelpFlag()
		flags := command.NonInheritedFlags()
		if flags.HasAvailableFlags() {
			output.WriteString("\nFlags:\n")
			output.WriteString(flags.FlagUsages())
		}
		if command.HasAvailableInheritedFlags() {
			output.WriteString("\nGlobal flags:\n")
			output.WriteString(command.InheritedFlags().FlagUsages())
		}
		output.WriteString("```\n\n")
	}
	return bytes.TrimSuffix(output.Bytes(), []byte("\n")), nil
}

func visibleCommands(root *cobra.Command) []*cobra.Command {
	commands := []*cobra.Command{root}
	var walk func(*cobra.Command)
	walk = func(parent *cobra.Command) {
		children := append([]*cobra.Command(nil), parent.Commands()...)
		sort.Slice(children, func(i, j int) bool { return children[i].Name() < children[j].Name() })
		for _, child := range children {
			if child.Hidden || child.Name() == "help" || !child.IsAvailableCommand() {
				continue
			}
			commands = append(commands, child)
			walk(child)
		}
	}
	walk(root)
	sort.SliceStable(commands[1:], func(i, j int) bool {
		return strings.Compare(commands[i+1].CommandPath(), commands[j+1].CommandPath()) < 0
	})
	return commands
}
