package docsgen

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/joshyorko/camp/internal/cli"
	"github.com/spf13/cobra"
)

// Generate renders repository documentation artifacts directly from the
// production Cobra tree. Paths are repository-relative and stable.
func Generate(root *cobra.Command) (map[string][]byte, error) {
	files := make(map[string][]byte)
	commands, err := commandReference(root)
	if err != nil {
		return nil, err
	}
	files["docs/generated/commands.md"] = commands
	for _, shell := range []cli.Shell{cli.ShellBash, cli.ShellZsh, cli.ShellFish} {
		var output bytes.Buffer
		if err := cli.GenerateCompletion(root, shell, &output); err != nil {
			return nil, fmt.Errorf("generate %s completion: %w", shell, err)
		}
		files[fmt.Sprintf("docs/generated/completions/camp.%s", shell)] = output.Bytes()
	}
	return files, nil
}

func commandReference(root *cobra.Command) ([]byte, error) {
	var output bytes.Buffer
	output.WriteString("<!-- Code generated by go run ./cmd/camp-docs; DO NOT EDIT. -->\n\n")
	output.WriteString("# Camp command reference\n\n")
	output.WriteString("This reference is generated from the production Cobra tree. A listed command is wired, but its presence is not evidence that external tools or a complete lifecycle succeeded.\n\n")
	commands := visibleCommands(root)
	for _, command := range commands {
		output.WriteString("## `" + command.CommandPath() + "`\n\n")
		output.WriteString(command.Short + "\n\n")
		output.WriteString("```text\nUsage:\n  " + command.UseLine() + "\n")
		flags := command.NonInheritedFlags()
		if flags.HasAvailableFlags() {
			output.WriteString("\nFlags:\n")
			output.WriteString(flags.FlagUsages())
		}
		if command.HasAvailableInheritedFlags() {
			output.WriteString("\nGlobal flags:\n")
			output.WriteString(command.InheritedFlags().FlagUsages())
		}
		output.WriteString("```\n\n")
	}
	return output.Bytes(), nil
}

func visibleCommands(root *cobra.Command) []*cobra.Command {
	commands := []*cobra.Command{root}
	var walk func(*cobra.Command)
	walk = func(parent *cobra.Command) {
		children := append([]*cobra.Command(nil), parent.Commands()...)
		sort.Slice(children, func(i, j int) bool { return children[i].Name() < children[j].Name() })
		for _, child := range children {
			if child.Hidden || child.Name() == "help" || !child.IsAvailableCommand() {
				continue
			}
			commands = append(commands, child)
			walk(child)
		}
	}
	walk(root)
	sort.SliceStable(commands[1:], func(i, j int) bool {
		return strings.Compare(commands[i+1].CommandPath(), commands[j+1].CommandPath()) < 0
	})
	return commands
}
