*** Settings ***
Resource         resources/candidate.resource
Suite Setup      Resolve Candidate Inputs
Test Setup       Prepare Isolated Controller
Test Teardown    Remove Isolated Controller

*** Variables ***
${BASH_COMPLETION_MARKER}    \# bash completion V2 for camp
${ZSH_COMPLETION_MARKER}     \#compdef camp
${FISH_COMPLETION_MARKER}    \# fish completion for camp

*** Test Cases ***
Root Help Exposes The Public Automation Surface
    [Tags]    req:CAMP-BB-HELP-001
    ${result}=    Run Candidate    ${TEST_ROOT}    --help
    Should Be Equal As Integers    ${result.rc}    0
    Should Contain    ${result.stdout}    Recoverable capsule workspaces
    Should Contain    ${result.stdout}    completion
    Should Contain    ${result.stdout}    init
    Should Contain    ${result.stdout}    list
    Should Contain    ${result.stdout}    status
    Should Contain    ${result.stdout}    --json

Shell Completions Are Generated By The Candidate
    [Tags]    req:CAMP-BB-COMPLETION-001
    [Template]    Candidate Completion Should Contain
    bash    ${BASH_COMPLETION_MARKER}
    zsh     ${ZSH_COMPLETION_MARKER}
    fish    ${FISH_COMPLETION_MARKER}

Unknown Command Failure Is Stable JSON
    [Tags]    req:CAMP-BB-JSON-ERROR-001
    ${result}=    Run Candidate
    ...    ${TEST_ROOT}
    ...    --json
    ...    definitely-not-a-command
    Should Not Be Equal As Integers    ${result.rc}    0
    ${payload}=    Parse Candidate JSON    ${result}
    Should Be Equal As Integers    ${payload}[schemaVersion]    1
    Should Be Equal    ${payload}[kind]    error
    Should Be Equal    ${payload}[error][code]    usage
    Should Contain    ${payload}[error][message]    unknown command
